# Generated by Django 5.0 on 2024-11-04 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_Webapp', '0002_appointment_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
