# Generated by Django 5.0 on 2024-11-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_Webapp', '0007_remove_appointment_appointment_id_appointment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.IntegerField(auto_created=True, default=1),
        ),
    ]
